version: '3.8'

services:
  boring_bot:
    build:
      context: .
    container_name: boring_bot
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/boringBot
      - ./app/credentials:/run/secrets:ro
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo_local
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
#    healthcheck:
#      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
#      interval: 60s
#      timeout: 5s
#      retries: 5
#      start_period: 5s

volumes:
  mongo_data:
